version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Compare-mobile
      runtime: node
      repo: https://github.com/amitbiswas00001234-cmyk/Compare-mobile
      plan: free
      region: oregon
      buildCommand: npm install
      startCommand: node server.js
      autoDeployTrigger: commit
      envVars:
        - key: GEMINI_API_KEY
          sync: false
